# Generated by Django 5.1.5 on 2025-02-21 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'EASY'), ('medium', 'MEDIUM'), ('hard', 'HARD')], max_length=6)),
                ('status', models.CharField(choices=[('in_progress', 'IN_PRORGESS'), ('completed', 'COMPLETED')], max_length=11)),
                ('solved_board_hash', models.CharField(max_length=64)),
                ('total_playtime', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'IN_PROGRESS'), ('completed', 'COMPLETED')], max_length=11)),
                ('board_state', models.JSONField()),
                ('solved_board', models.JSONField()),
                ('started_at', models.CharField(max_length=50, verbose_name='')),
                ('fail_count', models.IntegerField()),
                ('score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.scoremodel')),
            ],
        ),
    ]
